version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: size
        lines:
          max:
            count: 500
            message: Change is very large. Should be under 500 lines of addtions and deletions.
